# Generated by Django 5.1.2 on 2024-10-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='productname',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
